#pragma once
#include "paralyn/ir.hpp"
#include <array>
#include <cstddef>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

namespace paralyn {
// Trusted-local native shaders. This container validates the resource contract;
// Metal compilation/reflection validates the program and its actual signature.
// It is not a shader sandbox, nor a portable translation of arbitrary MSL.
// MslSource: container version 1, public MSL source (unchanged).
// SpirvMsl: container version 2, MSL generated by the pinned SPIR-V importer from
// a validated Vulkan 1.1 GLCompute module that the container also retains.
enum class ExecutableFormat : std::uint32_t { MslSource = 1, SpirvMsl = 2 };
// Origin of a SpirvMsl parameter. Always None for MslSource modules.
enum class ResourceOrigin : std::uint32_t {
  None = 0,
  StorageBuffer = 1, // Vulkan StorageBuffer block, one 32-bit scalar array
  UniformMember = 2, // one 32-bit scalar member of a Uniform block
  PushConstantMember = 3 // one 32-bit scalar member of the push-constant block
};
// Invocation builtins a SpirvMsl entry reads (bitmask). Zero for MslSource.
enum ExecutableBuiltin : std::uint32_t {
  BuiltinGlobalInvocationId = 1u << 0,
  BuiltinLocalInvocationId = 1u << 1,
  BuiltinLocalInvocationIndex = 1u << 2,
  BuiltinWorkgroupId = 1u << 3,
  BuiltinNumWorkgroups = 1u << 4,
  BuiltinWorkgroupSize = 1u << 5
};
inline constexpr std::uint32_t executable_builtin_mask = (1u << 6) - 1;
// SpirvMsl push-constant blocks bind at this Metal buffer slot.
inline constexpr std::uint32_t spirv_push_constant_slot = 30;
enum class ResourceAccess : std::uint32_t { Read = 1, Write = 2, ReadWrite = 3 };
struct ExecutableParameter {
  std::string name;
  ScalarType type = ScalarType::F32;
  bool buffer = true;
  ResourceAccess access = ResourceAccess::Read;
  std::uint32_t binding = 0;
  std::uint32_t alignment = 4;
  std::uint64_t minimum_bytes = 4;
  // SpirvMsl only. Scalars from one Uniform/push-constant block share `binding`
  // (their Metal slot) and are packed at `block_offset` bytes at launch.
  std::uint32_t block_offset = 0;
  ResourceOrigin origin = ResourceOrigin::None;
  std::uint32_t source_set = 0, source_binding = 0;
};
struct ExecutableEntry {
  std::string name;
  std::vector<ExecutableParameter> parameters;
  // All zero: any device-valid block. Otherwise the launch must match exactly.
  std::array<std::uint32_t, 3> required_block{0, 0, 0};
  std::uint32_t builtins = 0; // SpirvMsl only: ExecutableBuiltin bitmask
};
struct ExecutableModule {
  ExecutableFormat format = ExecutableFormat::MslSource;
  std::string target = "metal-msl3.1";
  // Safe math, precise functions, contraction off. Explicit MSL operations
  // retain their source semantics; this does not promise CUDA equivalence.
  std::uint32_t numerical_policy = 1;
  std::string producer;
  std::string producer_version;
  std::string source_name;
  std::string source_sha256;
  std::string source;
  std::vector<ExecutableEntry> entries;
  // SpirvMsl only: pinned importer toolchain identity and the exact validated
  // SPIR-V binary the MSL source was generated from.
  std::string toolchain;
  std::string spirv_sha256;
  std::vector<unsigned char> spirv;
};
inline constexpr std::size_t executable_max_bytes = 16 * 1024 * 1024;
inline constexpr std::size_t executable_max_source_bytes = 8 * 1024 * 1024;
inline constexpr std::size_t executable_max_spirv_bytes = 4 * 1024 * 1024;
std::string source_sha256(const std::string &source);
void verify_executable(const ExecutableModule &module);
std::vector<unsigned char> serialize_executable(const ExecutableModule &module);
ExecutableModule deserialize_executable(const void *data, std::size_t size);
bool is_executable_artifact(const void *data, std::size_t size) noexcept;
// Static storage-buffer use in a Logical-addressing SPIR-V binary, derived from
// OpLoad/OpStore/OpCopyMemory/atomic pointer roots (no library dependency, so
// the runtime can re-derive it from a container's retained SPIR-V). Returns
// set-0 binding -> ResourceAccess bits (0 when declared but unused). Rejects
// storage-buffer pointers passed to function calls, whose use it cannot bound.
// Fails closed: any other use of a storage-buffer-rooted pointer (for example
// the pointer operand of GLSL.std.450 Modf/Frexp) counts as read-write.
std::map<std::uint32_t, std::uint32_t> spirv_storage_buffer_access(
    const std::vector<unsigned char> &spirv);
} // namespace paralyn
