# Build-time provenance: runs on every build (not only at configure time) and
# rewrites the generated header only when the revision/dirty identity changes.
# Inputs: SOURCE_DIR, OUTPUT. No network access; a missing git yields "unknown".
set(commit "unknown")
set(dirty "unknown")
set(changes_sha256 "")
find_program(PARALYN_GIT git)
if(PARALYN_GIT)
  execute_process(COMMAND "${PARALYN_GIT}" -C "${SOURCE_DIR}" rev-parse HEAD
    OUTPUT_VARIABLE head RESULT_VARIABLE head_status OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
  if(head_status EQUAL 0 AND head MATCHES "^[0-9a-f]+$")
    set(commit "${head}")
    execute_process(COMMAND "${PARALYN_GIT}" -C "${SOURCE_DIR}" status --porcelain --untracked-files=normal
      OUTPUT_VARIABLE changes RESULT_VARIABLE status_status ERROR_QUIET)
    if(status_status EQUAL 0)
      if(changes)
        set(dirty "true")
        # Identifies tracked modifications plus the untracked-file list; untracked
        # file contents are not hashed.
        execute_process(COMMAND "${PARALYN_GIT}" -C "${SOURCE_DIR}" diff HEAD --binary
          OUTPUT_VARIABLE diff ERROR_QUIET)
        string(SHA256 changes_sha256 "${changes}\n${diff}")
      else()
        set(dirty "false")
      endif()
    endif()
  endif()
endif()
file(WRITE "${OUTPUT}.tmp"
"// Generated by cmake/build_info.cmake at build time. Do not edit.\n"
"#pragma once\n"
"#define PARALYN_EMBEDDED_REVISION \"${commit}\"\n"
"#define PARALYN_EMBEDDED_DIRTY \"${dirty}\"\n"
"#define PARALYN_EMBEDDED_CHANGES_SHA256 \"${changes_sha256}\"\n")
file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUTPUT}.tmp")
